name: ifyk_landing
description: "All Events One Place"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  auto_route: ^10.0.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^3.0.0
  flutter_riverpod: ^2.6.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.8.0
  smooth_page_indicator: ^1.2.1
  device_frame_plus: ^1.3.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^10.0.1
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3


# for updating launcher icons, run 'flutter pub run flutter_launcher_icons'
flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/png/app_icon.png"
    background_color: "#000000"

flutter:

  uses-material-design: true
  assets:
   - assets/png/
